using UnityEngine;
using System.Collections;

public enum GameDifficult {
	Easy,
	Normal,
	Hard
}

public class GameData : MonoBehaviour {

	public static GameDifficult Difficult { get; set; }
	public static string Theme { get; set; }
	public static string[] ThemeOptions { get; set; }

	public static string[] EasyThemes = {"COLORS"};
	public static string[] NormalThemes = {"COUNTRIES"};
	public static string[] HardThemes = {"SUPERHEROES"};

	public static string[] ThemeColors = {
		"BLUE",
		"BLACK",
		"RED",
		"ORANGE",
		"BROWN",
		"GRAY",
		"GREY",
		"WHITE",
		"PURPLE",
		"PINK",
		"GREEN",
		"YELLOW"
	};

	public static string[] ThemeCountries = {
		"AFGHANISTAN", 
		"ALBANIA", 
		"ALGERIA", 
		"ANDORRA", 
		"ANGOLA", 
		"ARGENTINA", 
		"ARMENIA", 
		"ARUBA", 
		"AUSTRALIA", 
		"AUSTRIA", 
		"AZERBAIJAN", 
		"BAHAMAS", 
		"BAHRAIN", 
		"BANGLADESH", 
		"BARBADOS", 
		"BELARUS", 
		"BELGIUM", 
		"BELIZE", 
		"BENIN", 
		"BHUTAN", 
		"BOLIVIA", 
		"BOSNIA", 
		"HERZEGOVINA", 
		"BOTSWANA", 
		"BRAZIL", 
		"BRUNEI", 
		"BULGARIA", 
		"BURKINA", 
		"BURMA", 
		"BURUNDI", 
		"CAMBODIA", 
		"CAMEROON", 
		"CANADA", 
		"CAPEVERDE", 
		"CHAD", 
		"CHILE", 
		"CHINA", 
		"COLOMBIA", 
		"COMOROS", 
		"CONGO", 
		"COSTARICA", 
		"COTEDIVOIRE", 
		"CROATIA", 
		"CUBA", 
		"CURACAO", 
		"CYPRUS", 
		"CZECHREPUBLIC", 
		"DENMARK", 
		"DJIBOUTI", 
		"DOMINICA", 
		"DOMINICANREPUBLIC", 
		"ECUADOR", 
		"EGYPT", 
		"ELSALVADOR", 
		"EQUATORIALGUINEA", 
		"ERITREA", 
		"ESTONIA", 
		"ETHIOPIA", 
		"FIJI", 
		"FINLAND", 
		"FRANCE", 
		"GABON", 
		"GAMBIA", 
		"GEORGIA", 
		"GERMANY", 
		"GHANA", 
		"GREECE", 
		"GRENADA", 
		"GUATEMALA", 
		"GUINEA", 
		"GUINEABISSAU", 
		"GUYANA", 
		"HAITI", 
		"HOLYSEE", 
		"HONDURAS", 
		"HONGKONG", 
		"HUNGARY", 
		"ICELAND", 
		"INDIA", 
		"INDONESIA", 
		"IRAN", 
		"IRAQ", 
		"IRELAND", 
		"ISRAEL", 
		"ITALY", 
		"JAMAICA", 
		"JAPAN", 
		"JORDAN", 
		"KAZAKHSTAN", 
		"KENYA", 
		"KIRIBATI", 
		"KOREA", 
		"KOSOVO", 
		"KUWAIT", 
		"KYRGYZSTAN", 
		"LAOS", 
		"LATVIA", 
		"LEBANON", 
		"LESOTHO", 
		"LIBERIA", 
		"LIBYA", 
		"LIECHTENSTEIN", 
		"LITHUANIA", 
		"LUXEMBOURG", 
		"MACAU", 
		"MACEDONIA", 
		"MADAGASCAR", 
		"MALAWI", 
		"MALAYSIA", 
		"MALDIVES", 
		"MALI", 
		"MALTA", 
		"MARSHALLISLANDS", 
		"MAURITANIA", 
		"MAURITIUS", 
		"MEXICO", 
		"MICRONESIA", 
		"MOLDOVA", 
		"MONACO", 
		"MONGOLIA", 
		"MONTENEGRO", 
		"MOROCCO", 
		"MOZAMBIQUE", 
		"NAMIBIA", 
		"NAURU", 
		"NEPAL", 
		"NETHERLANDS", 
		"NEWZEALAND", 
		"NICARAGUA", 
		"NIGER", 
		"NIGERIA", 
		"NORTHKOREA", 
		"NORWAY", 
		"OMAN", 
		"PAKISTAN", 
		"PALAU", 
		"PALESTINIAN", 
		"PANAMA", 
		"PAPUA", 
		"PAPUANEWGUINEA", 
		"PARAGUAY", 
		"PERU", 
		"PHILIPPINES", 
		"POLAND", 
		"PORTUGAL", 
		"QATAR", 
		"ROMANIA", 
		"RUSSIA", 
		"RWANDA", 
		"SAMOA", 
		"SANMARINO", 
		"SAOTOME", 
		"SAUDIARABIA", 
		"SENEGAL", 
		"SERBIA", 
		"SEYCHELLES", 
		"SIERRALEONE", 
		"SINGAPORE", 
		"SINTMAARTEN", 
		"SLOVAKIA", 
		"SLOVENIA", 
		"SOLOMONISLANDS", 
		"SOMALIA", 
		"SOUTHAFRICA", 
		"SOUTHKOREA", 
		"SOUTHSUDAN", 
		"SPAIN", 
		"SRILANKA", 
		"SUDAN", 
		"SURINAME", 
		"SWAZILAND", 
		"SWEDEN", 
		"SWITZERLAND", 
		"SYRIA", 
		"TAIWAN", 
		"TAJIKISTAN", 
		"TANZANIA", 
		"THAILAND", 
		"TIMORLESTE", 
		"TOGO", 
		"TONGA", 
		"TRINIDADANDTOBAGO", 
		"TUNISIA", 
		"TURKEY", 
		"TURKMENISTAN", 
		"TUVALU", 
		"UGANDA", 
		"UKRAINE", 
		"UNITEDARABEMIRATES", 
		"ARABEMIRATES", 
		"UNITEDKINGDOM", 
		"URUGUAY", 
		"UZBEKISTAN", 
		"VANUATU", 
		"VENEZUELA", 
		"VIETNAM", 
		"YEMEN", 
		"ZAMBIA", 
		"ZIMBABWE",
		"USA",
		"UNITEDSTATES"
	};

	public static string[] ThemeSuperHeroes = {
		"ADAMSTRANGE", 
		"AQUAMAN", 
		"BATGIRL", 
		"THEFLASH", 
		"FLASH", 
		"BATMAN", 
		"BEAST", 
		"BLACKCANARY", 
		"BLACKLIGHTNING", 
		"BLACKPANTHER", 
		"BLACKWIDOW", 
		"BLADE", 
		"BLUEBEETLE", 
		"BOOSTERGOLD", 
		"BUCKYBARNES", 
		"CAPTAINAMERICA", 
		"CAPTAINBRITAIN", 
		"CAPTAINMARVEL", 
		"CATWOMAN", 
		"CEREBUS", 
		"CYCLOPS", 
		"DAREDEVIL", 
		"DASHIELLBADHORSE", 
		"DEADPOOL", 
		"ROBIN", 
		"DONNATROY", 
		"DRSTRANGE", 
		"ELIJAHSNOW", 
		"ANTMAN", 
		"FONEBONE", 
		"GAMBIT", 
		"GHOSTRIDER", 
		"GREENARROW", 
		"GROO", 
		"GREENLANTERN", 
		"HAWKEYE", 
		"HAWKMAN", 
		"HELLBOY", 
		"HUMANTORCH", 
		"INVISIBLEWOMAN", 
		"IRONFIST", 
		"IRONMAN", 
		"JEANGREY", 
		"JESSEUSTER", 
		"JOHNCONSTANTINE", 
		"JONAHHEX", 
		"JUDGEDREDD", 
		"KAZAR", 
		"KITTYPRYDE", 
		"LUKECAGE", 
		"MARTIANMANHUNTER", 
		"MARV", 
		"MICHONNE", 
		"MITCHELLHUNDRED", 
		"MOONKNIGHT", 
		"NICKFURY", 
		"NIGHTCRAWLER", 
		"NOVA", 
		"PROFESSORX", 
		"PUNISHER", 
		"RAPHAEL", 
		"REEDRICHARDS", 
		"RENEEMONTOYA", 
		"RICKGRIMES", 
		"RORSCHACH", 
		"SAVAGEDRAGON", 
		"SCOTTPILGRIM", 
		"SGTROCK", 
		"SHEHULK", 
		"SILVERSURFER", 
		"SPAWN", 
		"SPIDERMAN", 
		"STORM", 
		"SUBMARINER", 
		"SUPERBOY", 
		"SUPERGIRL", 
		"SUPERMAN", 
		"SWAMPTHING", 
		"ATOM", 
		"CROW", 
		"FALCON", 
		"HULK", 
		"ROCKETEER", 
		"SPECTRE", 
		"SPIRIT", 
		"THING", 
		"TICK", 
		"THOR", 
		"USAGIYOJIMBO", 
		"WASP", 
		"WILDCAT", 
		"WOLVERINE", 
		"WONDERWOMAN", 
		"YORICKBROWN", 
		"KICKASS",
		"FLASHGORDON",
		"CHAPOLIN"
	};

	//TODO: Add more options to make this really random
	public static void SelectRandomTheme(GameDifficult pDifficult) {
		Difficult = pDifficult;

		switch (Difficult) {
			case GameDifficult.Easy:
				Theme = EasyThemes[0];
				ThemeOptions = ThemeColors;
				break;
			case GameDifficult.Normal:
				Theme = NormalThemes[0];
				ThemeOptions = ThemeCountries;
				break;
			case GameDifficult.Hard:
				Theme = HardThemes[0];
				ThemeOptions = ThemeSuperHeroes;
				break;
		}
	}
}
